[package]
name = "docker_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.12.0"
bollard = "0.11.0"
futures-util = "0.3.17"
chrono = "0.4.19"
